POST https://wenziopostgres.herokuapp.com/user/register
Content-Type: application/json

 {
     "user_email": "sendivyajyoti@gmail.com",
     "user_name" :"Divya",
     "user_password": "123456"
 }

###

POST https://wenziopostgres.herokuapp.com/User/login
Content-Type: application/json

 {
     "name": "idmsoamds",
     "password": "dsfsf"
 }

###

POST https://wenziopostgres.herokuapp.com/user/register
Content-Type: application/json

 {
     "name": "ama2n",
     "email": "aman2@gmail",
     "password": "789"
 }

###

POST https://wenziopostgres.herokuapp.com/user/login
Content-Type: application/json

 {
     "user_email": "shubruth8@gmail.com",
    "user_password": "Testing"
}

###
GET https://wenziopostgres.herokuapp.com/video/allVideos


###

GET https://wenziopostgres.herokuapp.com/users

 ###
 
DELETE https://wenziopostgres.herokuapp.com/user/logout

 Content-Type: application/json

