###
POST https://pure-tor-19634.herokuapp.com/user/register
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@email.com",
    "password": "user1"
}

###
POST https://pure-tor-19634.herokuapp.com/user/login
Content-Type: application/json

{
    "email": "user1@email.com",
    "password": "user1"
}

###
GET https://pure-tor-19634.herokuapp.com/user/all

###
DELETE https://pure-tor-19634.herokuapp.com/user/logout/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOGQzN2IwMDE4Mjg4MTdmY2M4M2E0YSIsImlhdCI6MTU4NjQzMDI3MywiZXhwIjoxNTg2NTE2NjczfQ.p6LTTUSKYR_ULjbQS04u8A0MnJjc8h239F3HuBFKKyg

###
POST https://pure-tor-19634.herokuapp.com/video/uploadVideo/:token
Content-Type: application/json

{
	"owner": "5e8d37b001828817fcc83a4a",
	"filePath": "uploads\\Otter.mp4_1586431870702",
    "title": "cute otter",
    "description": "cute otter description"
}

###
POST https://pure-tor-19634.herokuapp.com/subscribe/allSubscribedVideos/:token
Content-Type: application/json
{ 
	"fromUser": "5e8f36dbf49f30230065a456"	
}

###
POST https://pure-tor-19634.herokuapp.com/comment/getComments
Content-Type: application/json

{ 
	"videoId": "5e8f0a57ea79490734b740db"	
}

###
POST https://pure-tor-19634.herokuapp.com/comment/saveComment/:token
Content-Type: application/json
{ 
	"content": "some new comment response",
	"writer": "5e8d390401828817fcc83a4b",
	"videoId": "5e8f0a57ea79490734b740db",
	"responseTo": "5e8f24abb882112790a106e4"
}

###
POST https://pure-tor-19634.herokuapp.com/like/getLikes
Content-Type: application/json
{ 
	"videoId": "5e8f0a57ea79490734b740db"
}

###
POST https://pure-tor-19634.herokuapp.com/like/liked
Content-Type: application/json
{ 
    "userId": "5e8d390401828817fcc83a4b",
	"videoId": "5e8f0a57ea79490734b740db"
}

###

POST https://pure-tor-19634.herokuapp.com/video/uploadFile/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlOGYzNmRiZjQ5ZjMwMjMwMDY1YTQ1NiIsImlhdCI6MTU4NjQ5NzE0NiwiZXhwIjoxNTg2NTgzNTQ2fQ.jWa9avDZzG9enXnzlr_QCI0m8Kn4DzHE9SN17923t4o
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="Otter.mp4"
Content-Type: video/mp4

< C:\Users\Mucy\Desktop\Otter.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--
